name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install buildozer
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses6 \
          cmake \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer dependencies
      run: |
        sudo pip3 install buildozer
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Configure buildozer.spec
      run: |
        echo "[app]" >> buildozer.spec
        echo "title = KordHelp" >> buildozer.spec
        echo "package.name = kordhelp" >> buildozer.spec
        echo "package.domain = org.test" >> build
