name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install buildozer cython
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses6 \
          cmake \
          libffi-dev \
          libssl-dev \
          unzip

    - name: Install Buildozer dependencies
      run: |
        sudo pip3 install buildozer
        sudo apt-get install -y \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev

    - name: Install Android SDK
      run: |
        # Перевіряємо наявність wget і unzip
        which wget || (echo "wget not found" && exit 1)
        which unzip || (echo "unzip not found" && exit 1)
        # Завантажуємо Android Command Line Tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip || (echo "Failed to download commandlinetools" && exit 1)
        ls -la commandlinetools-linux-11076708_latest.zip
        # Розпаковуємо безпосередньо в android-sdk/cmdline-tools/latest
        mkdir -p android-sdk/cmdline-tools
        unzip commandlinetools-linux-11076708_latest.zip -d android-sdk/cmdline-tools/latest || (echo "Failed to unzip commandlinetools" && exit 1)
        rm commandlinetools-linux-11076708_latest.zip
        # Перевіряємо наявність sdkmanager
        ls -la android-sdk/cmdline-tools/latest/bin/sdkmanager
        # Оновлюємо SDK
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=android-sdk "platform-tools" "build-tools;33.0.0" "platforms;android-33" "extras;android;m2repository" "extras;google;m2repository" || (echo "Failed to run sdkmanager" && exit 1)
        # Перевіряємо, чи встановлено компоненти
        ls -la android-sdk/build-tools
        # Додаємо SDK до PATH
        echo "ANDROID_SDK_ROOT=$GITHUB_WORKSPACE/android-sdk" >> $GITHUB_ENV
        echo "$GITHUB_WORKSPACE/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "$GITHUB_WORKSPACE/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Initialize Buildozer
      run: |
        [ -f buildozer.spec ] && rm buildozer.spec
        buildozer init

    - name: Configure buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = KordHelp" >> buildozer.spec
        echo "package.name = kordhelp" >> buildozer.spec
        echo "package.domain = org.test" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,db,json,txt" >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3,kivy,sqlite3" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug
        ls -la bin/  # Перевіряємо вміст папки bin
        if [ -f "bin/kordhelp-*.apk" ]; then echo "APK found"; else echo "APK not found"; fi
