name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          openjdk-17-jdk \
          zlib1g-dev \
          libncurses6 \
          cmake \
          libffi-dev \
          libssl-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev \
          libportmidi-dev \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer

    - name: Initialize Buildozer
      run: buildozer init

    - name: Configure buildozer.spec
      run: |
        echo "[app]" > buildozer.spec
        echo "title = KordHelp" >> buildozer.spec
        echo "package.name = kordhelp" >> buildozer.spec
        echo "package.domain = org.test" >> buildozer.spec
        echo "source.dir = ." >> buildozer.spec
        echo "source.include_exts = py,png,jpg,kv,db,json,txt" >> buildozer.spec
        echo "version = 1.0" >> buildozer.spec
        echo "requirements = python3,kivy,sqlite3" >> buildozer.spec
        echo "android.permissions = INTERNET" >> buildozer.spec
        echo "android.api = 33" >> buildozer.spec
        echo "android.ndk = 25b" >> buildozer.spec
        echo "android.minapi = 21" >> buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug
        ls -la bin/

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kordhelp-apk
        path: bin/*.apk
